FROM jupyterhub/k8s-hub:0.9.0

LABEL maintainer="DigiKlausur (E2x) project HBRS <mohammad.wasil@h-brs.de>"

RUN pip3 install pandas
RUN pip3 install --no-cache-dir git+https://github.com/jupyterhub/nativeauthenticator.git@32ea9e7
