name: Test build and push to ghcr.io and quay.io

on:
  push:
    branches:
      - refactor_workflows_and_images
    paths:
      - .github/workflows/build_and_push_all_images.yml
      - .github/workflows/build_and_push_to_registry.yml
      - .github/workflows/build_e2xgrader_images.yml
      - .github/workflows/build_image.yml
      - images/**

jobs:
  
  build_and_push_to_ghcr:
    uses: ./.github/workflows/build_and_push_all_images.yml
    with:
      force_build: false
      push: true
      registry: ghcr.io
      tag: test
      e2xgrader_installation_source: pypi
    secrets: inherit

  build_and_push_to_quay:
    uses: ./.github/workflows/build_and_push_all_images.yml
    with:
      force_build: false
      push: true
      registry: quay.io
      tag: test
      e2xgrader_installation_source: pypi
    secrets: inherit
            
