name: Test build and push to ghcr.io

on:
  push:
    branches:
      refactor_workflows_and_images

jobs:
  
  manually_build_all_images:
    uses: ./.github/workflows/build_and_push_all_images.yml
    with:
      force_build: true
      push: true
      registry: ghcr.io
      tag: test
      e2xgrader_installation_source: pypi
            
