---
name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        bash ci/build-and-deploy.sh --deployment "" --registry ghcr.io

    - name: Docker image list
      run: docker images

  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        # GitHub container registry is still beta
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --publish latest

    - name: Docker image list
      run: docker images

  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: docker_deploy_prod
      run: |
        # GitHub container registry is still beta, just build
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --publish latest

    - name: Docker image list
      run: docker images
