---
name: CI to DockerHub
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  # Build image
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        bash .github/scripts/build-and-deploy.sh --deployment "" --registry "" 

    - name: Docker image list
      run: docker images

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        bash .github/scripts/build-and-deploy.sh --deployment dev --registry ""

    - name: Docker image list
      run: docker images

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and deploy image
      id: docker_deploy_prod
      run: |
        bash .github/scripts/build-and-deploy.sh --deployment prod --registry ""

    - name: Docker image list
      run: docker images
