---
name: Cronjob
on:
  schedule:
    - cron: "0 1 * * 0" 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        #cronjob build on docker hub to deal with their image retention policy
        bash ci/build-and-deploy.sh --deployment ""
