---
name: Hub
on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/hub.yml
      - hub/**
      - ci/**

jobs:
  build-and-publish-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and publish to ghcr.io
      id: docker_deploy_ghcr
      run: |
        bash ci/build-and-deploy-hub.sh --deployment development --registry ghcr.io/digiklausur/docker-stacks --publish

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publish to quay.io
      id: docker_deploy_quay
      run: |
        bash ci/build-and-deploy-hub.sh --deployment development --registry quay.io/digiklausur/docker-stacks --publish

  build-and-publish-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and publish to ghcr.io
      id: docker_deploy_ghcr
      run: |
        bash ci/build-and-deploy-hub.sh --deployment production --registry ghcr.io/digiklausur/docker-stacks --publish

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publish to quay.io
      id: docker_deploy_quay
      run: |
        bash ci/build-and-deploy-hub.sh --deployment production --registry quay.io/digiklausur/docker-stacks --publish
