---
name: Hub
on:
  pull_request:
  push:
    branches:
      - master
      - dev
    paths:
      - hub/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          bash ci/build-and-deploy.sh --deployment "prod" --registry ghcr.io --image hub--publish none
        else
          bash ci/build-and-deploy.sh --deployment "dev" --registry ghcr.io --image hub --publish none
        fi

    - name: Docker image list
      run: docker images

  build-and-publish:
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          bash ci/build-and-deploy.sh --deployment "prod" --registry ghcr.io --image hub --publish latest
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          bash ci/build-and-deploy.sh --deployment "dev" --registry ghcr.io --image hub --publish latest
        else
          echo "Cannot build from current branch"
        fi

    - name: Docker image list
      run: docker images
