name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy dev
      if: github.event.inputs.branch == 'dev'
      id: docker_deploy_dev
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --publish latest

    - name: Build and deploy prod
      if: github.event.inputs.branch == 'master'
      id: docker_deploy_prod
      run: |
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --publish latest

    - name: Docker image list
      run: docker images
