name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev'
      image:
        descriptiion: 'Image to build'
        required: true
        default: 'all'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and publish to ghcr.io
      id: build_and_deploy
      run: |
        BRANCH=${{ needs.event.inputs.branch }}
        IMAGE=${{ needs.event.inputs.image }}

        if [ "$BRANCH" == "dev" ]; then
          bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image $IMAGE --publish latest
        elif [ "$BRANCH" == "master" ]; then
          bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --image $IMAGE --publish latest
        else
          echo "Branch $BRANCH unknown"
          exit 1
        fi
        
    - name: Login to Quay Container Registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publish to quay.io
      id: build_and_deploy_to_quay
      run: |
        BRANCH=${{ needs.event.inputs.branch }}
        IMAGE=${{ needs.event.inputs.image }}

        if [ "$BRANCH" == "dev" ]; then
          bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image $IMAGE --publish latest
        elif [ "$BRANCH" == "master" ]; then
          bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --image $IMAGE --publish latest
        else
          echo "Branch $BRANCH unknown"
          exit 1
        fi
