---
name: Ngshare
on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/**
      - hub/**
      - ci/**

jobs:
  build-and-publish-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and publish to ghcr.io
      id: build_and_deploy_to_ghcr
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image ngshare --publish latest

    - name: Login to Quay Container Registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publish to quay.io
      id: build_and_deploy_to_quay
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image ngshare --publish latest

  build-and-publish-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and publish to ghcr.io
      id: build_and_deploy_to_ghcr
      run: |
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --image ngshare --publish latest

    - name: Login to Quay Container Registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publish to ghcr.io
      id: build_and_deploy_to_quay
      run: |
        bash ci/build-and-deploy.sh --deployment prod --registry quay.io --image ngshare --publish latest
