---
name: Notebook
on:
  workflow_run:
    workflows: ["Datascience Notebook"]
    types:
      - completed
  pull_request:
  push:
    branches:
      - master
      - dev
    paths:
      - notebook/**

jobs:
  build-and-publish-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image notebook --publish latest

    - name: Docker image list
      run: docker images

  build-and-publish-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: docker_deploy_prod
      run: |
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --image notebook --publish latest

    - name: Docker image list
      run: docker images
