---
name: Notebook Dev
on:
  push:
    branches:
      - dev
    paths:
      - .github/**
      - ci/**
      - minimal-notebook/**
      - datascience-notebook/**
      - notebook/**
      - exam-notebook/**

jobs:
  notebook:
    name: Notebook
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and publish to ghcr.io
      id: build_and_publish_to_ghcr
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image all-notebook --publish latest

    - name: Login to Quay Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publish to quay.io
      id: build_and_publish_to_quay
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry quay.io --image all-notebook --publish latest

