---
name: Pull Request
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: build_image
      run: |
        bash ci/build-and-deploy.sh --deployment dev --registry ghcr.io --image all --publish none
