---
name: Deploy tags
on:
  push:
    tags:
      - 'ws*'
      - 'ss*'
      - 'release-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and publis to ghcr.io
      id: docker_build_publish_ghcr
      run: |
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --image all --version ${{ steps.get_version.outputs.VERSION }} --publish version

    - name: Login to Quay Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_SECRET }}

    - name: Build and publis to quay.io
      id: docker_build_publish_quay
      run: |
        bash ci/build-and-deploy.sh --deployment prod --registry quay.io --image all --version ${{ steps.get_version.outputs.VERSION }} --publish version
