---
name: Deploy tags
on:
  push:
    tags:
      - 'ws*'
      - 'ss*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build image
      id: docker_build
      run: |
        # deploy images for specific tag
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --version ${{ steps.get_version.outputs.VERSION }} --publish version

    - name: Docker image list
      run: docker images
