---
name: Deploy tags
on:
  create:
    tags:
      - 'ws*'
      - 'ss*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        # deploy images for specific tag
        bash ci/build-and-deploy.sh --deployment prod --registry ghcr.io --publish version

    - name: Docker image list
      run: docker images
